cd_pipeline:
  runs-on: ubuntu-latest
  needs: [ci_pipeline]

  env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPO_NAME: ${{ secrets.REPO_NAME }}

  steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image
      run: |
        REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        docker build . --file Dockerfile --tag "$DOCKER_USER/$REPO_NAME_LOWER:${{ steps.date.outputs.date }}"

    - name: Docker Push
      run: |
        REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        docker push "$DOCKER_USER/$REPO_NAME_LOWER:${{ steps.date.outputs.date }}"
